#!/bin/bash

export ENV_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export PROJECT_PATH=$(cd $ENV_PATH && cd .. && pwd )
export PROJECT_DIR=$(basename $PROJECT_PATH)
echo -e "Activating environment for ${PROJECT_DIR} ..."
export ENV_OLD_PATH=$PATH
export PATH=$PROJECT_PATH/node_modules/.bin:/$PATH
export ENV_OLD_PS1=$PS1
export PS1="(${PROJECT_DIR})${PS1}"
alias deactivate="source ${ENV_PATH}/deactivate"
 
